spring:
  application:
    name: coupon-issue
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54325/sample
    username: sample
    password: 1234
  data:
    redis:
      host: localhost
      port: 63795
      username: default
      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # sql 로깅
        format_sql: true # SQL 문 정렬하여 출력
        highlight_sql: true # SQL 문 색 부여
        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시
